Models/DetalleInscripciones.cs
namespace Inscripcioness.Models
{
    public class DetalleInscripciones
    {
        public int Id { get; set; }
        public int ModalidadCursado { get; set; }
        public int InscripcionId { get; set; }
        public Inscripcion Inscripcion { get; set; }
        public int MateriaId { get; set; }
        public Materia Materia { get; set; }
    }
}

Controllers/DetalleInscripcionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Inscripcioness.Models;

namespace Inscripcioness.Controllers
{
    public class DetalleInscripcionesController : Controller
    {
        private readonly InscripcionesContext _context;

        public DetalleInscripcionesController(InscripcionesContext context)
        {
            _context = context;
        }

        // GET: DetalleInscripciones
        public async Task<IActionResult> Index()
        {
            var inscripcionesContext = _context.DetalleInscripciones.Include(d => d.Inscripcion).Include(d => d.Materia);
            return View(await inscripcionesContext.ToListAsync());
        }

        // GET: DetalleInscripciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleInscripciones = await _context.DetalleInscripciones
                .Include(d => d.Inscripcion)
                .Include(d => d.Materia)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (detalleInscripciones == null)
            {
                return NotFound();
            }

            return View(detalleInscripciones);
        }

        // GET: DetalleInscripciones/Create
        public IActionResult Create()
        {
            ViewData["InscripcionId"] = new SelectList(_context.Inscripciones, "Id", "Id");
            ViewData["MateriaId"] = new SelectList(_context.Materia, "Id", "Id");
            return View();
        }

        // POST: DetalleInscripciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModalidadCursado,InscripcionId,MateriaId")] DetalleInscripciones detalleInscripciones)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detalleInscripciones);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["InscripcionId"] = new SelectList(_context.Inscripciones, "Id", "Id", detalleInscripciones.InscripcionId);
            ViewData["MateriaId"] = new SelectList(_context.Materia, "Id", "Id", detalleInscripciones.MateriaId);
            return View(detalleInscripciones);
        }

        // GET: DetalleInscripciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleInscripciones = await _context.DetalleInscripciones.FindAsync(id);
            if (detalleInscripciones == null)
            {
                return NotFound();
            }
            ViewData["InscripcionId"] = new SelectList(_context.Inscripciones, "Id", "Id", detalleInscripciones.InscripcionId);
            ViewData["MateriaId"] = new SelectList(_context.Materia, "Id", "Id", detalleInscripciones.MateriaId);
            return View(detalleInscripciones);
        }

        // POST: DetalleInscripciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ModalidadCursado,InscripcionId,MateriaId")] DetalleInscripciones detalleInscripciones)
        {
            if (id != detalleInscripciones.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detalleInscripciones);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetalleInscripcionesExists(detalleInscripciones.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InscripcionId"] = new SelectList(_context.Inscripciones, "Id", "Id", detalleInscripciones.InscripcionId);
            ViewData["MateriaId"] = new SelectList(_context.Materia, "Id", "Id", detalleInscripciones.MateriaId);
            return View(detalleInscripciones);
        }

        // GET: DetalleInscripciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleInscripciones = await _context.DetalleInscripciones
                .Include(d => d.Inscripcion)
                .Include(d => d.Materia)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (detalleInscripciones == null)
            {
                return NotFound();
            }

            return View(detalleInscripciones);
        }

        // POST: DetalleInscripciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var detalleInscripciones = await _context.DetalleInscripciones.FindAsync(id);
            if (detalleInscripciones != null)
            {
                _context.DetalleInscripciones.Remove(detalleInscripciones);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DetalleInscripcionesExists(int id)
        {
            return _context.DetalleInscripciones.Any(e => e.Id == id);
        }
    }
}

Views/DetalleInscripciones/Create.cshtml
@model Inscripcioness.Models.DetalleInscripciones

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DetalleInscripciones</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModalidadCursado" class="control-label"></label>
                <input asp-for="ModalidadCursado" class="form-control" />
                <span asp-validation-for="ModalidadCursado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InscripcionId" class="control-label"></label>
                <select asp-for="InscripcionId" class ="form-control" asp-items="ViewBag.InscripcionId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MateriaId" class="control-label"></label>
                <select asp-for="MateriaId" class ="form-control" asp-items="ViewBag.MateriaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DetalleInscripciones/Delete.cshtml
@model Inscripcioness.Models.DetalleInscripciones

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetalleInscripciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModalidadCursado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModalidadCursado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inscripcion.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Materia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Materia.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/DetalleInscripciones/Details.cshtml
@model Inscripcioness.Models.DetalleInscripciones

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DetalleInscripciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModalidadCursado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModalidadCursado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inscripcion.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Materia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Materia.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/DetalleInscripciones/Edit.cshtml
@model Inscripcioness.Models.DetalleInscripciones

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DetalleInscripciones</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ModalidadCursado" class="control-label"></label>
                <input asp-for="ModalidadCursado" class="form-control" />
                <span asp-validation-for="ModalidadCursado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InscripcionId" class="control-label"></label>
                <select asp-for="InscripcionId" class="form-control" asp-items="ViewBag.InscripcionId"></select>
                <span asp-validation-for="InscripcionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MateriaId" class="control-label"></label>
                <select asp-for="MateriaId" class="form-control" asp-items="ViewBag.MateriaId"></select>
                <span asp-validation-for="MateriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DetalleInscripciones/Index.cshtml
@model IEnumerable<Inscripcioness.Models.DetalleInscripciones>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModalidadCursado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inscripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Materia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModalidadCursado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inscripcion.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Materia.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/DetalleInscripciones/IndexPorInscripcion.cshtml
@model IEnumerable<Inscripcioness.Models.DetalleInscripciones>

@{
    ViewData["Title"] = "Index";
    int idinscripcion = ViewBag.IdInscripcion;
}

<h1>Index</h1>

<p>
    <a asp-action="CreateConInscripcion" asp-route-idinscripcion="@idinscripcion">Create New</a>
</p>

<form asp-controller="DetalleInscripciones" asp-action="IndexPorInscripcion">
    <div class="form-group">
        <label asp-for="@idinscripcion" class="control-label"></label>
        <select asp-for="@idinscripcion" class="form-control" asp-items="ViewBag.Inscripciones" disabled onchange="this.form.submit()"></select>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModalidadCursado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Materia.AnioCarrera)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Materia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ModalidadCursado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Materia.AnioCarrera.AñoYCarrera)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Materia.Nombre)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>